"""trial 3

Revision ID: 0e33ce98a18b
Revises: 
Create Date: 2023-05-24 09:16:51.862887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e33ce98a18b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('report_bug', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nominal_dana', sa.Integer(), nullable=True),
    sa.Column('durasi_hari', sa.Integer(), nullable=True),
    sa.Column('nilai_warung', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['akun.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pemberi_rekomendasi',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_warung', sa.String(), nullable=True),
    sa.Column('lokasi_warung', sa.String(), nullable=True),
    sa.Column('jam_buka_warung', sa.String(), nullable=True),
    sa.Column('kontak_warung', sa.Integer(), nullable=True),
    sa.Column('nama_makanan', sa.String(), nullable=True),
    sa.Column('harga_makanan', sa.Integer(), nullable=True),
    sa.Column('nama_minuman', sa.String(), nullable=True),
    sa.Column('harga_minuman', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['akun.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pemberi_rekomendasi')
    op.drop_table('mahasiswa')
    op.drop_table('akun')
    # ### end Alembic commands ###
