"""trial 6

Revision ID: 28c76c936bec
Revises: 
Create Date: 2023-05-30 08:57:31.778006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c76c936bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_item', sa.String(), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('harga_item', sa.Integer(), nullable=True),
    sa.Column('nama_warung', sa.String(), nullable=True),
    sa.Column('lokasi_warung', sa.String(), nullable=True),
    sa.Column('jam_buka_warung', sa.Time(), nullable=True),
    sa.Column('jam_tutup_warung', sa.Time(), nullable=True),
    sa.Column('alamat_warung', sa.String(), nullable=True),
    sa.Column('kontak_warung', sa.String(), nullable=True),
    sa.Column('foto_warung', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nominal_dana', sa.Integer(), nullable=True),
    sa.Column('durasi_hari', sa.Integer(), nullable=True),
    sa.Column('nilai_warung', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['akun.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('pemberi_rekomendasi',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['akun.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pemberi_rekomendasi')
    op.drop_table('mahasiswa')
    op.drop_table('warung')
    op.drop_table('report_bug')
    op.drop_table('akun')
    # ### end Alembic commands ###
